title: Dr.Mw
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5625
  brandStrength: 0.25
  rhythmicContrast: 0.75
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-44711168-2
  facebook: null
name: Marwan
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.58675
layout_spectrum: 1
