name: Marwan
favicon: null
layout_spectrum: 0.88885
typography_spectrum: 0.58675
title: "Marwan Alzarouni's Grid-O-Matic!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44711168-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1875
  lightness: 0.706365785561502
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
