name: Marwan
favicon: null
layout_spectrum: 0.7190615788567811
typography_spectrum: 0.2989919849205762
title: "Marwan Alzarouni's Grid-O-Matic!"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-44711168-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4750536377541721
  lightness: 0.706365785561502
  saturation: 0.4462366921361536
  rhythmicContrast: 0.12169313500635326
purpose: []
